package pojos;

import java.util.Date;

/**
 * Person generated by hbm2java
 */
public class Person implements java.io.Serializable {
	
	private Integer idPerson;
	private String login;
	private String password;
	private Date puttime;

	public Person() {
	}

	public Person(String login, String password, Date puttime) {
		this.login = login;
		this.password = password;
		this.puttime = puttime;
	}

	public Integer getIdPerson() {
		return this.idPerson;
	}

	public void setIdPerson(Integer idPerson) {
		this.idPerson = idPerson;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getPuttime() {
		return this.puttime;
	}

	public void setPuttime(Date puttime) {
		this.puttime = puttime;
	}

}
